name: Build vanilla ZSTD

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Move dh_jni_forwarder
        run: mv ./dhjni ./app/src/main/zstd/src/main/native/
      - name: Add dhjni folder to CMake
        run: git apply ./CMakeLists.patch
      - name: Build
        run: ./gradlew :app:assembleRelease
      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: zstd-release
          path: app/build/outputs/aar/app-release.aar

